#! /bin/sh

set -e

echo "=> Installing Pip and dependencies...\n"
sudo apt install -y python3-pip
sudo pip3 install -r requirements.txt

echo "=> Installing MusicBox motion detector...\n"
sudo cp musicbox-motion-detector /usr/local/bin/
sudo chmod +x /usr/local/bin/musicbox-motion-detector

echo "=> Starting MusicBox motion detector via Systemd...\n"
sudo cp musicbox-motion-detector.service /lib/systemd/system/musicbox-motion-detector.service

sudo systemctl daemon-reload
sudo systemctl enable musicbox-motion-detector.service
sudo systemctl restart musicbox-motion-detector.service

echo "MusicBox motion detector installed."
